CREATE VIEW VW_CLIENTE AS
	SELECT COD_FUNC, IDADE_FUNC, NOME_FUNC	
		FROM funcionario
			WHERE IDADE_FUNC >=50

CREATE VIEW VW_FINANCEIRO AS
	SELECT BONUS_FUNC, SAL_FUNC	
		FROM funcionario	
			WHERE COD_FUNC = 8;

UPDATE VW_FINANCEIRO 
	SET BONUS_FUNC = 100
	SET SAL_FUNC = 1000
		WHERE COD_FUNC = 8;

DELETE VW_FINANCEIRO WHERE COD_FUNC=8

Delete VW_FINANCEIRO,